### PR TITLE
Add Project Name in Blueprint Info and Refactoring App Deploy REST APIs

### PR DESCRIPTION
**Pull request by Durgesh1988**

### CODE REVIEW

**Comment by gobindadas** [comment]
@Durgesh1988 : The api which is giving nexus,docker and tasks response together should not be part of routes_appdeploy the API should be the part of routes_d4dmasters.Please rectify it.

**Comment by Durgesh1988** [comment]
Resolved Pull Request comments

**Comment by gobindadas** [comment]
@Durgesh1988 : The api (/d4dMasters/organization/:orgId/businessgroup/:bgId/project/:projectId/environment/:envId/newAppDeploy) does not describe valid meaning.Change to valid end point w.r.t. what it does.
And /newAppDeploy is meaningless for this API.

**Comment by Durgesh1988** [comment]
changed end point w.r.t. functionality and meaning.

**Comment by gobindadas** [comment]
Thanks

**Pull request merged**
