### PR TITLE
Jquery and server side code added. 

### PR DESCRIPTION
**Pull request by srikanthv02**
@revinjacob : The cat3 jquery and server side cde has been added to this branch. Tested and able to hit the url. Kindly verify it once.

### CODE REVIEW

**Comment by revinjacob** [comment]
Pls recheck what is catalog.html. Also jQuery index.html shows lot of diff, due to formatting perhaps. Please correct them.

**Comment by revinjacob** [comment]
angular index.html shows lot of changes likewise, while none are expected in this index file

**Comment by srikanthv02** [comment]
@revinjacob : Catalog.html has been removed. No issues with the angular index.html. It is all fine. You can  go ahead with the merge i guess.

**Comment by srikanthv02** [comment]
@revinjacob : Reverted back angular index.html to PR #69

**Comment by srikanthv02** [comment]
@revinjacob : 	Formatted angular index.html using html formatter.

**Comment by srikanthv02** [comment]
Closing the old pull request as a new branch has been created(jquerychanges) for adding the jquery and server side changes and a new pull request was raised.
@revinjacob , @kkn , @Kaushik512 .

**Pull request closed without merging**
